name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: zerotier-ssh
      run: |
        touch /tmp/keepalive
        sudo wget https://raw.githubusercontent.com/hsunsfire/GAssh/master/zs && chmod +x zs && ./zs

    - name: SSH connection to Actions
      uses: hsunsfire/debugger-action@master
