name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: zerotier-ssh
      run: |
        touch /tmp/keepalive
        sudo apt-get update
        sudo apt-get -y install screen
        echo "root:password" | chpasswd
        curl -s https://install.zerotier.com | sudo bash
        sudo zerotier-cli join b6079f73c643e466
        echo "PermitRootLogin yes" | cat >> /etc/ssh/sshd_config

    - name: SSH connection to Actions
      uses: hsunsfire/debugger-action@master
