name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: zerotier-ssh
      run: |
        touch /tmp/keepalive
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf screen
        sudo echo "root:password" | chpasswd
        curl -s https://install.zerotier.com | sudo bash
        sudo zerotier-cli join b6079f73c643e466
        sudo echo "PermitRootLogin yes" | cat >> /etc/ssh/sshd_config
        sudo /etc/init.d/ssh restart

    - name: SSH connection to Actions
      uses: hsunsfire/debugger-action@master
